# Generated by Django 3.2.25 on 2025-11-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente Inmobiliario',
                'verbose_name_plural': 'Agentes Inmobiliarios',
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de Subasta')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Inicial')),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio de Reserva')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Actual')),
                ('min_bid_increment', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Incremento Mínimo de Puja')),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio Compra Ya')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Finalización')),
                ('auto_extend', models.BooleanField(default=True, verbose_name='Extensión Automática')),
                ('extend_minutes', models.PositiveIntegerField(default=5, verbose_name='Minutos de Extensión')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('active', 'Activa'), ('ended', 'Finalizada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('require_deposit', models.BooleanField(default=False, verbose_name='Requiere Depósito')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto de Depósito')),
                ('allow_proxy_bidding', models.BooleanField(default=True, verbose_name='Permitir Pujas Automáticas')),
                ('total_bids', models.PositiveIntegerField(default=0, verbose_name='Total de Pujas')),
                ('total_bidders', models.PositiveIntegerField(default=0, verbose_name='Total de Participantes')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Subasta',
                'verbose_name_plural': 'Subastas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('bid_type', models.CharField(choices=[('manual', 'Manual'), ('proxy', 'Automática'), ('buy_now', 'Compra Ya')], default='manual', max_length=20, verbose_name='Tipo de Puja')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Máximo Automático')),
                ('is_proxy_active', models.BooleanField(default=False, verbose_name='Puja Automática Activa')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('is_winning', models.BooleanField(default=False, verbose_name='Es Ganadora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='properties.auction', verbose_name='Subasta')),
            ],
            options={
                'verbose_name': 'Puja',
                'verbose_name_plural': 'Pujas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('transaction_type', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Arriendo'), ('auction', 'Subasta'), ('both', 'Venta y Arriendo')], default='sale', max_length=10, verbose_name='Tipo de Transacción')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Baños')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área Total (m²)')),
                ('area_built', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Construida (m²)')),
                ('floors', models.PositiveIntegerField(default=1, verbose_name='Pisos')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='Parqueaderos')),
                ('age_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Antigüedad (años)')),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio Venta')),
                ('price_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio Arriendo')),
                ('price_admin', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Administración')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Piscina')),
                ('has_gym', models.BooleanField(default=False, verbose_name='Gimnasio')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Jardín')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcón')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='Ascensor')),
                ('has_security', models.BooleanField(default=False, verbose_name='Vigilancia')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Amoblado')),
                ('allows_pets', models.BooleanField(default=False, verbose_name='Acepta Mascotas')),
                ('main_image', models.ImageField(upload_to='properties/', verbose_name='Imagen Principal')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.agent', verbose_name='Agente')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.city', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Estado')),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#10b981', max_length=7, verbose_name='Color hex')),
            ],
            options={
                'verbose_name': 'Estado de Propiedad',
                'verbose_name_plural': 'Estados de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='bi-house', max_length=50, verbose_name='Ícono Bootstrap')),
            ],
            options={
                'verbose_name': 'Tipo de Propiedad',
                'verbose_name_plural': 'Tipos de Propiedades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(verbose_name='Fecha Preferida')),
                ('preferred_time', models.TimeField(verbose_name='Hora Preferida')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('agent_notes', models.TextField(blank=True, null=True, verbose_name='Notas del Agente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.client', verbose_name='Cliente')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Solicitud de Visita',
                'verbose_name_plural': 'Solicitudes de Visitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Visita a Propiedad',
                'verbose_name_plural': 'Visitas a Propiedades',
            },
        ),
        migrations.CreateModel(
            name='PropertyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', verbose_name='Imagen')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Galería de Fotos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertystatus', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='properties.client', verbose_name='Cliente')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Consulta de Contacto',
                'verbose_name_plural': 'Consultas de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Acción')),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Anterior')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Nuevo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_history', to='properties.auction', verbose_name='Subasta')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='properties.bid', verbose_name='Puja')),
            ],
            options={
                'verbose_name': 'Historial de Puja',
                'verbose_name_plural': 'Historial de Pujas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='properties.client', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='AuctionWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_bid', models.BooleanField(default=True, verbose_name='Notificar Nueva Puja')),
                ('notify_outbid', models.BooleanField(default=True, verbose_name='Notificar al ser Superado')),
                ('notify_ending_soon', models.BooleanField(default=True, verbose_name='Notificar Próximo a Finalizar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='properties.auction', verbose_name='Subasta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_auctions', to='properties.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Seguidor de Subasta',
                'verbose_name_plural': 'Seguidores de Subastas',
            },
        ),
        migrations.CreateModel(
            name='AuctionDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='auction_deposits/', verbose_name='Comprobante')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Notas del Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='properties.auction', verbose_name='Subasta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_deposits', to='properties.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Depósito de Subasta',
                'verbose_name_plural': 'Depósitos de Subastas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='properties.property', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='properties.client', verbose_name='Ganador'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction', to='properties.bid', verbose_name='Puja Ganadora'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'property_type'], name='properties__city_id_d98010_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_sale'], name='properties__price_s_307392_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_rent'], name='properties__price_r_02bf1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('client', 'property')},
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount'], name='properties__auction_e3cc97_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['client', '-created_at'], name='properties__client__683e8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionwatcher',
            unique_together={('auction', 'client')},
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'start_date'], name='properties__status_461c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['end_date'], name='properties__end_dat_c40383_idx'),
        ),
    ]
